### PR TITLE
Browserify usage instructions

### PR DESCRIPTION
**Pull request by jesstelford**
I've figured out how to get it all running smoothly in the browser, so I've documented it here. If you feel it should go somewhere else, or not even be documented; your call :)

Thanks for working with me on #6 #7, & #8 to get this running!

### CODE REVIEW

**Comment by roman01la** [comment]
Thanks! I'll probably move it into Wiki later, but for now it's ok to have this in readme.

**Comment by roman01la** [comment]
FYI, I've added a new section into readme to mention your extension https://github.com/roman01la/html-to-react-components#browser-extension

**Comment by jesstelford** [comment]
Oh wow, thanks for adding that! Hopefully it's something the community will enjoy using once I publish the extension :)

**Comment by jesstelford** [comment]
I think this is all the changes from me for now - will you publish a new npm version?

**Comment by roman01la** [comment]
yes, just published as v1.4.0

**Pull request merged**
